### ISSUE TITLE
程序排版乱了

### ISSUE THREAD

**Issue by fakongo** [emqx/blog#1017]
File: [/zh/201911/upload-sensor-data-to-mqtt-cloud-service-via-nodemcu-esp8266.md](https://www.emqx.com/zh/blog/upload-sensor-data-to-mqtt-cloud-service-via-nodemcu-esp8266)

**Comment by fakongo** [comment]
“7.完整代码”里面有的程序排版乱了
![image](https://github.com/emqx/blog/assets/43336812/0d047b5c-9588-41d3-a3e9-f5debb7324b7)

**Comment by CrazyWisdom** [comment]
> “7.完整代码”里面有的程序排版乱了 ![image](https://private-user-images.githubusercontent.com/43336812/288790255-0d047b5c-9588-41d3-a3e9-f5debb7324b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMjA1MzksIm5iZiI6MTcwMjAyMDIzOSwicGF0aCI6Ii80MzMzNjgxMi8yODg3OTAyNTUtMGQwNDdiNWMtOTU4OC00MWQzLWEzZTktZjVkZWJiNzMyNGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDA3MjM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZGVmMGY5MjE1ZDY5YzkyMjBmY2RiM2FiZDA5Zjg4MTUxNjczNjNhNGM5NjQ3NDI5YmE3NTBlOTM0MzBkMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7r7cO418jE6C9H4fRypuAI04V-ruaGdc2TY4eDlFeok)

已更新。非常感谢您的提醒！
