### ISSUE TITLE
共享那一块的跳转链接错了

### ISSUE THREAD

**Issue by TrinityLeaves** [emqx/blog#1021]
File: [/zh/202209/advanced-features-of-mqtt-topics.md](https://www.emqx.com/zh/blog/advanced-features-of-mqtt-topics)

**Comment by CrazyWisdom** [comment]
> File: [/zh/202209/advanced-features-of-mqtt-topics.md](https://www.emqx.com/zh/blog/advanced-features-of-mqtt-topics)

已更新。
非常感谢您的提醒！
