### ISSUE TITLE
MQTT-Explorer development seems to be quite active?

### ISSUE THREAD

**Issue by berlincount** [emqx/blog#1242]
File: [/en/202401/mqtt-client-tools.md](https://www.emqx.com/en/blog/mqtt-client-tools)

https://github.com/thomasnordquist/MQTT-Explorer/commits/master/

The post says otherwise.

**Comment by ysfscream** [comment]
Hi, @berlincount. Thanks for your reminder and attention!

When we wrote the blog post, MQTT Explorer had indeed stopped receiving updates for a while. There appear to have been new commits recently, which we had not noticed before. We will update and revise the relevant content in the blog as we're supposed to. Thanks again for bringing this to our attention!
