### ISSUE TITLE
Disingenuous license comparison

### ISSUE THREAD

**Issue by siepkes** [emqx/blog#1247]
File: [/en/202304/emqx-vs-vernemq-2023-mqtt-broker-comparison.md](https://www.emqx.com/en/blog/emqx-vs-vernemq-2023-mqtt-broker-comparison)

Calling both EMQX and VerneMQ "Apache License 2.0" in the above blogpost is at best a half truth. In reality EMQX is only partly open-source (it's "opencore" strictly speaking). Basic functionality like persistence is covered under the BUSL license which by itself states: "The Business Source License is not an Open Source license." and says the work is only allowed to be used for "non-production". Not even mentioning there are parts of EMQX which are not opensource is quite frankly just disingenuous.

BTW I'm not affiliated with VerneMQ.

**Comment by wivwiv** [comment]
Thank you for your question. I'd like to clarify the following:

EMQX is divided into two editions: the open-source edition (EMQX) and the enterprise edition (EMQX Enterprise). The source code of the open-source edition is fully open-sourced under the Apache License 2.0, allowing distribution and usage in compliance with the license terms.

For users, you can download the binary package from our official website or build from source code using the `make emqx` command to get the "pure" open-source edition.

In fact, this is a common challenge and approach for all commercialized open-source software, e.g [Elasticsearch](https://github.com/elastic/elasticsearch?tab=License-1-ov-file).


> Not even mentioning there are parts of EMQX which are not opensource is quite frankly just disingenuous.

Each code file's header clearly indicates the type of license it falls under. For example:

- Apache License 2.0: [emqx_mqtt.hrl](https://github.com/emqx/emqx/blob/master/apps/emqx/include/emqx_mqtt.hrl#L8)
- BUSL: [emqx_bridge_kafka.erl](https://github.com/emqx/emqx/blob/master/apps/emqx_bridge_kafka/src/emqx_bridge_kafka.erl#L2)

> Basic functionality like persistence is covered under the BUSL license

In fact, this functionality is open source and is planned to be GA in v5.7.0. It remains consistent in both the open-source and enterprise editions.
[source code](https://github.com/emqx/emqx/blob/master/apps/emqx/src/emqx_persistent_session_ds.erl#L8)

**Comment by zmstone** [comment]
Thank you for bringing this to our attention.
My colleague will update the blog post to make it clear that only EMQX Opensource edition is released under Apache 2 license.
Session message persistence is included in Opensource edition version 5.
