### ISSUE TITLE
How about safety, is that any security potential issue should be worried? with using free public broker

### ISSUE THREAD

**Issue by Ma-0325** [emqx/blog#1332]
File: [/en/202306/esp32-connects-to-the-free-public-mqtt-broker.md](https://www.emqx.com/en/blog/esp32-connects-to-the-free-public-mqtt-broker)

**Comment by CrazyWisdom** [comment]
> File: [/en/202306/esp32-connects-to-the-free-public-mqtt-broker.md](https://www.emqx.com/en/blog/esp32-connects-to-the-free-public-mqtt-broker)

Hi, there is a notice on the [public broker page](https://www.emqx.com/en/mqtt/public-mqtt5-broker): Please note the message sent to the public MQTT broker is visible to all connected clients. Please do NOT use it for production.

<img width="1410" alt="image" src="https://github.com/user-attachments/assets/342a55e2-909b-4b5c-8f7d-de9521fdf52c" />
