### ISSUE TITLE
怎么没有V5版本的示例啊

### ISSUE THREAD

**Issue by chengjianqiang5** [emqx/blog#1388]
File: [/zh/202208/how-to-use-mqtt-in-java.md](https://www.emqx.com/zh/blog/how-to-use-mqtt-in-java)

**Comment by CrazyWisdom** [comment]
> File: [/zh/202208/how-to-use-mqtt-in-java.md](https://www.emqx.com/zh/blog/how-to-use-mqtt-in-java)

您好，现在已经更新了 V5 的代码。
谢谢您的建议！
