### ISSUE TITLE
haproxy长连接超过6.4W后

### ISSUE THREAD

**Issue by vonboe** [emqx/blog#141]
File: [/zh/202101/emqx-haproxy.md](https://www.emqx.com/zh/blog/emqx-haproxy)
请问haproxy 负载均衡EMQX超过6.4W以后需要额外增加网卡来连接集群吗

**Comment by zmstone** [comment]
Hello @vonboe 
抱歉没留意到这里的issue。
但是 64K 源端口上限可以通过增加（虚拟）IP地址来解决。
不过不是很确定有没有其他更好的办法。
