### ISSUE TITLE
Interesting but confusing

### ISSUE THREAD

**Issue by AngeloHulshout** [emqx/blog#1447]
File: [/en/202407/connecting-mqtt-and-rest-api.md](https://www.emqx.com/en/blog/connecting-mqtt-and-rest-api)

This is interesting but also confusing. Does EMQX offer the HTTP interface, or is this article hypotheical?

**Comment by cherryxkz** [comment]
Hello, In our document, there is a brief overview of the HTTP interface provided by EMQX：https://docs.emqx.com/en/enterprise/v5.8/admin/api-docs.html

**Comment by AngeloHulshout** [comment]
Yep, I found that yesterday also in the EMQX documentation. First implementation based on publish is already done. Defining a full blown applicaiton specific REST interface is not within EMQX scope I suspect (wouldn't be if I was the maintainer), but this works very well for us.

**Comment by AngeloHulshout** [comment]
Question answered.
