### ISSUE TITLE
SSL/TLS 双向连接的启用及验证

### ISSUE THREAD

**Issue by jsk970** [emqx/blog#212]
File: [/zh/202007/enable-two-way-ssl-for-emqx.md](https://www.emqx.com/zh/blog/enable-two-way-ssl-for-emqx)

文中开启TLS双向验证，EMQX配置文件需修改配置，校验客户端是否传证书文件。
##
## Value: true | false
listener.ssl.external.fail_if_no_peer_cert = true

此配置默认注释，文中未提到此配置需为true。未开启状态下，双向验证客户端未传证书文件也可连接成功。

**Comment by CrazyWisdom** [comment]
> File: [/zh/202007/enable-two-way-ssl-for-emqx.md](https://www.emqx.com/zh/blog/enable-two-way-ssl-for-emqx)
> 
> 文中开启TLS双向验证，EMQX配置文件需修改配置，校验客户端是否传证书文件。
> 
> ## Used together with {verify, verify_peer} by an SSL server. If set to true,
> ## the server fails if the client does not have a certificate to send, that is,
> ## sends an empty certificate.
> ## Value: true | false
> listener.ssl.external.fail_if_no_peer_cert = true
> 
> 此配置默认注释，文中未提到此配置需为true。未开启状态下，双向验证客户端未传证书文件也可连接成功。

已更新：https://github.com/emqx/blog/pull/213/files。

谢谢反馈。
