### ISSUE TITLE
mqtt-jmeter插件相关问题

### ISSUE THREAD

**Issue by wxg0103** [emqx/blog#235]
mqtt-jmeter插件现在还维护吗？
有些订阅的问题想要了解一下

**Comment by CrazyWisdom** [comment]
> mqtt-jmeter插件现在还维护吗？
> 有些订阅的问题想要了解一下

你好，还在维护的，你可以直接在项目 https://github.com/emqx/mqtt-jmeter/issues 里面提issue。
