### ISSUE TITLE
表格格式错了

### ISSUE THREAD

**Issue by HappyAxin** [emqx/blog#342]
File: [/zh/201903/mqtt5-message-publishing-process.md](https://www.emqx.com/zh/blog/mqtt5-message-publishing-process)
表格格式显示错误了

**Comment by CrazyWisdom** [comment]
> File: [/zh/201903/mqtt5-message-publishing-process.md](https://www.emqx.com/zh/blog/mqtt5-message-publishing-process) 表格格式显示错误了

已更新，感谢您的提醒。
