### ISSUE TITLE
EMQX + IoTDB：存储 MQTT 消息到时序数据库

### ISSUE THREAD

**Issue by jiangnan12** [emqx/blog#368]
File: [/zh/202201/store-mqtt-messages-to-time-series-database-iotdb.md](https://www.emqx.com/zh/blog/store-mqtt-messages-to-time-series-database-iotdb)
如果是集群的话，loTDB 如何配置呢

**Comment by terry-xiaoyu** [comment]
参考一下 IoTDB 集群搭建的文档吧：https://iotdb.apache.org/zh/UserGuide/V0.11.x/Server/Cluster%20Setup.html
