### ISSUE TITLE
"MicroPython MQTT Tutorial Based on Raspberry Pi" - Installation of micropython fails

### ISSUE THREAD

**Issue by DeeJay** [emqx/blog#399]
File: [/en/202209/micro-python-mqtt-tutorial-based-on-raspberry-pi.md](https://www.emqx.com/en/blog/micro-python-mqtt-tutorial-based-on-raspberry-pi)

I am running the 64-bit version of RasPiOS Bullseye. Installation of micropython fails with

pi@rpitest64:~ $ sudo apt install micropython -s
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package micropython
pi@rpitest64:~ $

(apt update has been run immediately prior to this.)

There does not seem to be any trace of 'micropython' in the Debian packages index for any release of Debian.

{Update: I have also tried the 32-bit version of RasPiOS Bullseye with the same (failed) result.}

**Comment by CrazyWisdom** [comment]
> File: [/en/202209/micro-python-mqtt-tutorial-based-on-raspberry-pi.md](https://www.emqx.com/en/blog/micro-python-mqtt-tutorial-based-on-raspberry-pi)
> 
> I am running the 64-bit version of RasPiOS Bullseye. Installation of micropython fails with
> 
> pi@rpitest64:~ $ sudo apt install micropython -s Reading package lists... Done Building dependency tree... Done Reading state information... Done E: Unable to locate package micropython pi@rpitest64:~ $
> 
> (apt update has been run immediately prior to this.)
> 
> There does not seem to be any trace of 'micropython' in the Debian packages index for any release of Debian.
> 
> {Update: I have also tried the 32-bit version of RasPiOS Bullseye with the same (failed) result.}


Hi DeeJay,

We have just updated the blog and you can now refer to the MicroPython installation section to install it. If the installation still fails, please let me know.

Thanks!
