### ISSUE TITLE
Connection Settings not working

### ISSUE THREAD

**Issue by ajw2060** [emqx/blog#410]
The example provided for connection settings differs from the example shown in the php-mqtt repository (below).  The example provided here does not apply the connection settings and therefore any broker expecting a username and password will return an error 5.  The emqx broker appears not to need credentials so the example here does run but the Connection Settings are not encoded.  This is evident from looking at the Connect packet in Wireshark, where it shows the Connect Flags not correctly set.

$connectionSettings = (new \PhpMqtt\Client\ConnectionSettings)
    ->setConnectTimeout(3)
    ->setUseTls(true)
    ->setTlsSelfSignedAllowed(true);

**Comment by wivwiv** [comment]
Yes, our sample code is wrong, please see this pr for the right example
https://github.com/emqx/MQTT-Client-Examples/pull/59
