### ISSUE TITLE
the author of HBMQTT states it is no longer maintained

### ISSUE THREAD

**Issue by skewty** [emqx/blog#449]
File: [/en/202104/python-async-mqtt-client-hbmqtt.md](https://www.emqx.com/en/blog/python-async-mqtt-client-hbmqtt)

Please adjust the suggestion to https://github.com/Yakifo/amqtt and ensure a note exists that as of the time of this writing only Python 3.9 is supported.

**Comment by CrazyWisdom** [comment]
> /en/202104/python-async-mqtt-client-hbmqtt.md

The blog has been updated. Thank you for your suggestion.
