### ISSUE TITLE
incorrect command for helm EMQ X EE deployment with license

### ISSUE THREAD

**Issue by qzhuyan** [emqx/blog#49]
File: [/en/201910/rapidly-deploy-emqx-clusters-on-kubernetes-via-helm.md](https://www.emqx.io/blog/rapidly-deploy-emqx-clusters-on-kubernetes-via-helm)

replace
```
$ helm install my-emqx-ee emqx/emqx-ee emqxLicneseSecretName=your-license-secret-name
```

with 
```
$ helm install my-emqx-ee emqx/emqx-ee --set emqxLicneseSecretName=your-license-secret-name
```

**Comment by CrazyWisdom** [comment]
https://github.com/emqx/blog/pull/88

> File: [/en/201910/rapidly-deploy-emqx-clusters-on-kubernetes-via-helm.md](https://www.emqx.io/blog/rapidly-deploy-emqx-clusters-on-kubernetes-via-helm)
> 
> replace
> 
> ```
> $ helm install my-emqx-ee emqx/emqx-ee emqxLicneseSecretName=your-license-secret-name
> ```
> 
> with
> 
> ```
> $ helm install my-emqx-ee emqx/emqx-ee --set emqxLicneseSecretName=your-license-secret-name
> ```

https://github.com/emqx/blog/pull/88
