### ISSUE TITLE
neuron-dashboard和neuron版本兼容问题

### ISSUE THREAD

**Issue by xufei2222** [emqx/blog#501]
File: [/zh/202212/how-to-cross-compile-neuron-source-code.md](https://www.emqx.com/zh/blog/how-to-cross-compile-neuron-source-code)

你好，
有时候会遇到neuron-dashboard和neuron版本不兼容问题，能否创建一个neuron-dashboard的详细构建文档，谢谢。

**Comment by lixiumei123** [comment]
中文：可使用 neuron-dashboard 的发版包，请参考 [neuron-dashboard releases](https://github.com/emqx/neuron-dashboard/releases)。
2.3 版本后，neuron 与 neuron-dashboard 都有中间版的分支，保证 neuron 和 neuron-dashboard 的中间分支一致，应该就不会有问题了。
neuron 的 main 与 neuron-dashboard 的 master 分支相对应，都是处于开发阶段的分支。

English：You can use the released version package of [neuron-dashboard](https://github.com/emqx/neuron-dashboard/releases).
After version 2.3, both neuron and neuron-dashboard have intermediate branches, so there should be no problem if the intermediate branches of neuron and neuron-dashboard are consistent.
The main of neuron corresponds to the master branch of neuron-dashboard, both of which are in the development stage.
