### ISSUE TITLE
这个需要提供V5版本和springboot整合的那种

### ISSUE THREAD

**Issue by xiezhuolong** [emqx/blog#517]
File: [/zh/202208/how-to-use-mqtt-in-java.md](https://www.emqx.com/zh/blog/how-to-use-mqtt-in-java)

**Comment by CrazyWisdom** [comment]
> File: [/zh/202208/how-to-use-mqtt-in-java.md](https://www.emqx.com/zh/blog/how-to-use-mqtt-in-java)

您好，已提供V5版本代码。
