### ISSUE TITLE
请问如何直接使用mqtt协议进行连接

### ISSUE THREAD

**Issue by tigerjiang** [emqx/blog#518]
`const options = {
  host: 'broker.emqx.io',
  port: 8083,
  path: '/testTopic',
  id: 'id_' + parseInt(Math.random() * 100000),
  useSSL: false,
};`

我看到代码里面使用的是8083端口号,使用的是websocket进行了链接,我想问的是如何配置mqtt端口号进行连接呢

**Comment by CrazyWisdom** [comment]
> `const options = { host: 'broker.emqx.io', port: 8083, path: '/testTopic', id: 'id_' + parseInt(Math.random() * 100000), useSSL: false, };`
> 
> 我看到代码里面使用的是8083端口号,使用的是websocket进行了链接,我想问的是如何配置mqtt端口号进行连接呢

你好，请问你看的是哪篇博客？mqtt 的默认端口是 1883。
