### ISSUE TITLE
HAProxy+emqx集群, ssl连接使用`listener.ssl.external.peer_cert_as_username=dn`配置失效

### ISSUE THREAD

**Issue by hhyouyou** [emqx/blog#57]
File: [/zh/202101/emqx-haproxy.md](https://www.emqx.cn/blog/emqx-haproxy)

### 问题描述
按照文档,成功部署了,HAProxy + emqx的集群. tcp和ssl连接都能正常使用.
但是碰到一个问题: 不使用集群直连时可以通过配置文件中的`listener.ssl.external.peer_cert_as_username = dn` 配置项, 以证书中的SubAltName做为客户端username. 但是通过HAProxy, 使用ssl连接时,username并不是 证书中的字段, 仍然是client连接时的原始username. 

### 环境
系统为uos基于Linux version 4.19.0-desktop-amd64
emqx版本为emqx-ubuntu18.04-4.3.3-amd64.deb
HAProxy 版本 2.4.0

### haproxy配置方式:
backend backend_emqx_ssl
    mode tcp
    balance roundrobin
    server emqx_node_1 10.4.17.134:8883 check-send-proxy send-proxy-v2 check inter 10s fall 2 rise 5
    server emqx_node_2 10.4.17.141:8883 check-send-proxy send-proxy-v2 check inter 10s fall 2 rise 5
frontend frontend_emqx_ssl
    bind *:8005 
    option tcplog
    mode tcp
    default_backend backend_emqx_ssl
(剩余配置略)

是否需要在emqx中做额外配置?或者在HAProxy做配置,让emqx broker能正确解析证书字段? 

希望尽快回复,谢谢.

**Comment by zibuyu1995** [comment]
使用 haproxy 做tls 终结，只支持发送证书 CN，你需要在haproxy 配置中加入 send-proxy-v2-ssl-cn，emqx 同步修改 listener.tcp.external.peer_cert_as_username = cn

**Comment by hhyouyou** [comment]
谢谢解答,我尝试下 CN 的获取.
