### ISSUE TITLE
示例代码有一处缺陷

### ISSUE THREAD

**Issue by xiaoyegu** [emqx/blog#621]
File: [/zh/202101/esp8266_mqtt_led.md](https://www.emqx.com/zh/blog/esp8266_mqtt_led)
1.经测试应该在setup里面添加pinMode(LED, OUTPUT);以设置引脚才能有效控制
2.判断led开关的逻辑貌似有问题，为什么on是digitalWrite(LED, LOW);而off相反 >-<

**Comment by zibuyu1995** [comment]
您好，为了方便识别，我们已修改了示例代码参阅: https://github.com/emqx/MQTT-Client-Examples/blob/master/mqtt-client-ESP8266/esp_mqtt_led.ino
