### ISSUE TITLE
编译jwt时报错

### ISSUE THREAD

**Issue by hualaihu** [emqx/blog#714]
File: [/zh/202212/how-to-cross-compile-neuron-source-code.md](https://www.emqx.com/zh/blog/how-to-cross-compile-neuron-source-code)

报错如下：
root@100ask:/opt/module/libjwt/build# make
[ 12%] Building C object libjwt/CMakeFiles/jwt.dir/jwt-openssl.c.o
In file included from /usr/include/openssl/bio.h:13:0,
                 from /opt/module/libjwt/libjwt/jwt-openssl.c:12:
/usr/include/openssl/e_os2.h:13:11: fatal error: openssl/opensslconf.h: No such file or directory
 # include <openssl/opensslconf.h>

**Comment by lixiumei123** [comment]
需要安装 openssl 。
可以参考最新的依赖包安装说明 [install-dependencies](https://github.com/emqx/neuron/blob/main/Install-dependencies.md)
