### ISSUE TITLE
failed to run custom build command for `openssl-sys v0.9.93`

### ISSUE THREAD

**Issue by Locter9001** [emqx/blog#902]
File: [/zh/202010/how-to-use-mqtt-in-rust.md](https://www.emqx.com/zh/blog/how-to-use-mqtt-in-rust)

**Comment by oucb** [comment]
Please check if the paho-mqtt version is 0.7.1，paho-mqtt 0.7.1 does not support [openssl-sys](https://crates.io/crates/openssl-sys)，you can refer to here https://github.com/eclipse/paho.mqtt.rust/tree/v0.7.1#building-the-paho-c-library-with-or-without-ssltls

**Comment by Locter9001** [comment]
okay! thanks I got it
