### ISSUE TITLE
Incorrect claims about AWS IoT Core

### ISSUE THREAD

**Issue by gregbreen** [emqx/blog#971]
Hello. This blog has some claims that could do with correction: https://github.com/emqx/blog/blob/main/en/202309/aws-mqtt-managing-iot-communication-in-aws.md#emqx-cloud-vs-aws-iot-core

Some points:

* AWS IoT Core supports MQTT 5. Differences from standards: https://docs.aws.amazon.com/iot/latest/developerguide/mqtt.html#mqtt-differences
* There is no vendor lock-in with the AWS IoT Device SDKs. You can use many third party MQTT clients (https://aws.amazon.com/blogs/iot/use-aws-iot-core-mqtt-broker-with-standard-mqtt-libraries/) to connect to AWS IoT Core, and you can use AWS IoT Device SDKs with MQTT brokers other than AWS IoT Core.
* You can integrate with non AWS services. For instance using this rule action: https://docs.aws.amazon.com/iot/latest/developerguide/https-rule-action.html. 
* AWS IoT Core [quotas and limits](https://docs.aws.amazon.com/general/latest/gr/iot-core.html#message-broker-limits) help guard against "bill shock".
* Maximum concurrent client connections of 500,000 is a soft limit that can be raised.

**Comment by azuregaya** [comment]
Thanks for bringing up the information. We've updated the blog with accurate descriptions.

**Comment by gregbreen** [comment]
Thank you
